import type { Metadata } from "next";
import { Playfair_Display, Open_Sans } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/components/cart/context";
import { CurrentUserProvider } from "@/components/current-user";
import { getCurrentUser } from "@/services/auth/current-user";

const titleFont = Playfair_Display({
  subsets: ["latin"],
  weight: ["500", "600"],
  variable: "--title-font",
});

const normalFont = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--normal-font",
});
const className = `${normalFont.variable} ${titleFont.variable}`;
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();
  return (
    <html lang="en">
      <body className={className}>
        <CurrentUserProvider user={user}>
          <CartProvider>{children}</CartProvider>
        </CurrentUserProvider>
      </body>
    </html>
  );
}
