import type { Metadata } from "next";
import { Playfair_Display, Open_Sans } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/components/cart/context";
import { CurrentUserProvider } from "@/components/current-user";
import {
  getCurrentUser,
  setCurrentUserAdmin,
} from "@/services/auth/current-user";
import { getCookie } from "@/actions";
import { ACCESS_TOKEN_COOKIE_KEY } from "@/constants";
import { cookies } from "next/headers";
import { User } from "@/types/user";

const titleFont = Playfair_Display({
  subsets: ["latin"],
  weight: ["500", "600"],
  variable: "--title-font",
});

const normalFont = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--normal-font",
});
const className = `${normalFont.variable} ${titleFont.variable}`;
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const accessToken = cookies().get(ACCESS_TOKEN_COOKIE_KEY)?.value ?? null;
  const user = (await getCurrentUser(accessToken ?? "")) as User;
  if (user) setCurrentUserAdmin(accessToken ?? "", user?.id);
  return (
    <html lang="en">
      <body className={className}>
        <CurrentUserProvider user={user} accessToken={accessToken}>
          <CartProvider>{children}</CartProvider>
        </CurrentUserProvider>
      </body>
    </html>
  );
}
